/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Squidex } from "@squidex/squidex";

export interface AssetsDto extends Squidex.Resource {
    /** The total number of assets. */
    total?: number;
    /** The assets. */
    items: Squidex.AssetDto[];
}
