/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export type BulkUpdateAssetType = "Annotate" | "Move" | "Delete";

export const BulkUpdateAssetType = {
    Annotate: "Annotate",
    Move: "Move",
    Delete: "Delete",
} as const;
