/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateAssetFolderDto {
    /** The name of the folder. */
    folderName: string;
    /** The ID of the parent folder. */
    parentId?: string;
}
