/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Squidex from "../../../../../api";
import * as core from "../../../../../core";

export const RestoreRequestDto: core.serialization.Schema<
    serializers.RestoreRequestDto.Raw,
    Squidex.RestoreRequestDto
> = core.serialization.object({
    name: core.serialization.string().optional(),
    url: core.serialization.string(),
});

export declare namespace RestoreRequestDto {
    interface Raw {
        name?: string | null;
        url: string;
    }
}
