/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Squidex from "../../../..";

export interface AssetsGetAssetFoldersRequest {
    /**
     * The optional parent folder id.
     */
    parentId?: string;
    /**
     * The scope of the query.
     */
    scope?: Squidex.AssetFolderScope;
}
