/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DeleteAssetRequest {
    /**
     * True to check referrers of this asset.
     */
    checkReferrers?: boolean;
    /**
     * True to delete the asset permanently.
     */
    permanent?: boolean;
}
