/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Squidex } from "@fern-api/squidex";

export interface GetAssetFoldersRequest {
    /**
     * The optional parent folder id.
     */
    parentId?: string;
    /**
     * The scope of the query.
     */
    scope?: Squidex.AssetFolderScope;
}
