/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RenameAssetFolderDto {
    /** The name of the folder. <span style="white-space: nowrap">`non-empty`</span> */
    folderName: string;
}
