/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ArrayFieldPropertiesDto {
    /** The minimum allowed items for the field value. */
    minItems?: number;
    /** The maximum allowed items for the field value. */
    maxItems?: number;
    /** The fields that must be unique. */
    uniqueFields?: string[];
}
