/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export type DateTimeFieldEditor = "Date" | "DateTime";

export const DateTimeFieldEditor = {
    Date: "Date",
    DateTime: "DateTime",
} as const;
