/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Squidex } from "@squidex/squidex";

export type FieldPropertiesDto =
    | Squidex.FieldPropertiesDto.Array
    | Squidex.FieldPropertiesDto.Assets
    | Squidex.FieldPropertiesDto.Boolean
    | Squidex.FieldPropertiesDto.Component
    | Squidex.FieldPropertiesDto.Components
    | Squidex.FieldPropertiesDto.DateTime
    | Squidex.FieldPropertiesDto.Geolocation
    | Squidex.FieldPropertiesDto.Json
    | Squidex.FieldPropertiesDto.Number
    | Squidex.FieldPropertiesDto.References
    | Squidex.FieldPropertiesDto.String
    | Squidex.FieldPropertiesDto.Tags
    | Squidex.FieldPropertiesDto.Ui;

export declare namespace FieldPropertiesDto {
    interface Array extends Squidex.ArrayFieldPropertiesDto, _Base {
        fieldType: "Array";
    }

    interface Assets extends Squidex.AssetsFieldPropertiesDto, _Base {
        fieldType: "Assets";
    }

    interface Boolean extends Squidex.BooleanFieldPropertiesDto, _Base {
        fieldType: "Boolean";
    }

    interface Component extends Squidex.ComponentFieldPropertiesDto, _Base {
        fieldType: "Component";
    }

    interface Components extends Squidex.ComponentsFieldPropertiesDto, _Base {
        fieldType: "Components";
    }

    interface DateTime extends Squidex.DateTimeFieldPropertiesDto, _Base {
        fieldType: "DateTime";
    }

    interface Geolocation extends Squidex.GeolocationFieldPropertiesDto, _Base {
        fieldType: "Geolocation";
    }

    interface Json extends Squidex.JsonFieldPropertiesDto, _Base {
        fieldType: "Json";
    }

    interface Number extends Squidex.NumberFieldPropertiesDto, _Base {
        fieldType: "Number";
    }

    interface References extends Squidex.ReferencesFieldPropertiesDto, _Base {
        fieldType: "References";
    }

    interface String extends Squidex.StringFieldPropertiesDto, _Base {
        fieldType: "String";
    }

    interface Tags extends Squidex.TagsFieldPropertiesDto, _Base {
        fieldType: "Tags";
    }

    interface Ui extends Squidex.UiFieldPropertiesDto, _Base {
        fieldType: "UI";
    }

    interface _Base {
        /** Optional label for the editor. */
        label?: string;
        /** Hints to describe the field. */
        hints?: string;
        /** Placeholder to show when no value has been entered. */
        placeholder?: string;
        /** Indicates if the field is required. */
        isRequired?: boolean;
        /** Indicates if the field is required when publishing. */
        isRequiredOnPublish?: boolean;
        /** Indicates if the field should be rendered with half width only. */
        isHalfWidth?: boolean;
        /** Optional url to the editor. */
        editorUrl?: string;
        /** Tags for automation processes. */
        tags?: string[];
    }
}
