/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SchemaPropertiesDto {
    /** Optional label for the editor. */
    label?: string;
    /** Hints to describe the schema. */
    hints?: string;
    /** The url to a the sidebar plugin for content lists. */
    contentsSidebarUrl?: string;
    /** The url to a the sidebar plugin for content items. */
    contentSidebarUrl?: string;
    /** The url to the editor plugin. */
    contentEditorUrl?: string;
    /** True to validate the content items on publish. */
    validateOnPublish?: boolean;
    /** Tags for automation processes. */
    tags?: string[];
}
