/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SquidexApi } from "@fern-api/squidex";

export interface SynchronizeSchemaDto extends SquidexApi.UpsertSchemaDto {
    /** True, when fields should not be deleted. */
    noFieldDeletion?: boolean;
    /** True, when fields with different types should not be recreated. */
    noFieldRecreation?: boolean;
}
