/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SquidexApi } from "@fern-api/squidex";
import * as core from "../../../../core";

export const PlansLockedReason: core.serialization.Schema<
    serializers.PlansLockedReason.Raw,
    SquidexApi.PlansLockedReason
> = core.serialization.enum_(["None", "NotOwner", "NoPermission", "ManagedByTeam"]);

export declare namespace PlansLockedReason {
    type Raw = "None" | "NotOwner" | "NoPermission" | "ManagedByTeam";
}
