/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SquidexApi } from "@fern-api/squidex";
import * as core from "../../../../core";

export const ReferralInfo: core.serialization.ObjectSchema<serializers.ReferralInfo.Raw, SquidexApi.ReferralInfo> =
    core.serialization.object({
        code: core.serialization.string().optional(),
        earned: core.serialization.string().optional(),
        condition: core.serialization.string().optional(),
    });

export declare namespace ReferralInfo {
    interface Raw {
        code?: string | null;
        earned?: string | null;
        condition?: string | null;
    }
}
