/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Squidex } from "@fern-api/squidex";
import * as core from "../../../../core";

export const BooleanFieldPropertiesDto: core.serialization.ObjectSchema<
    serializers.BooleanFieldPropertiesDto.Raw,
    Squidex.BooleanFieldPropertiesDto
> = core.serialization.object({
    defaultValues: core.serialization
        .lazy(async () => (await import("../../..")).LocalizedValueOfNullableBoolean)
        .optional(),
    defaultValue: core.serialization.boolean().optional(),
    inlineEditable: core.serialization.boolean().optional(),
    editor: core.serialization.lazy(async () => (await import("../../..")).BooleanFieldEditor).optional(),
});

export declare namespace BooleanFieldPropertiesDto {
    interface Raw {
        defaultValues?: serializers.LocalizedValueOfNullableBoolean.Raw | null;
        defaultValue?: boolean | null;
        inlineEditable?: boolean | null;
        editor?: serializers.BooleanFieldEditor.Raw | null;
    }
}
