/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Squidex } from "@squidex/squidex";
import * as core from "../../../../core";

export const ConfigureUiFieldsDto: core.serialization.ObjectSchema<
    serializers.ConfigureUiFieldsDto.Raw,
    Squidex.ConfigureUiFieldsDto
> = core.serialization.object({
    fieldsInLists: core.serialization.list(core.serialization.string()).optional(),
    fieldsInReferences: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace ConfigureUiFieldsDto {
    interface Raw {
        fieldsInLists?: string[] | null;
        fieldsInReferences?: string[] | null;
    }
}
