/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Squidex } from "@squidex/squidex";
import * as core from "../../../../core";

export const StringContentType: core.serialization.Schema<
    serializers.StringContentType.Raw,
    Squidex.StringContentType
> = core.serialization.enum_(["Unspecified", "Html", "Markdown"]);

export declare namespace StringContentType {
    type Raw = "Unspecified" | "Html" | "Markdown";
}
