/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Squidex } from "@fern-api/squidex";
import * as core from "../../../../core";

export const UpdateFieldDto: core.serialization.ObjectSchema<serializers.UpdateFieldDto.Raw, Squidex.UpdateFieldDto> =
    core.serialization.object({
        properties: core.serialization.lazyObject(async () => (await import("../../..")).FieldPropertiesDto),
    });

export declare namespace UpdateFieldDto {
    interface Raw {
        properties: serializers.FieldPropertiesDto.Raw;
    }
}
