/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SquidexApi } from "@fern-api/squidex";

export interface BackupJobDto extends SquidexApi.Resource {
    /** The ID of the backup job. */
    id?: string;
    /** The time when the job has been started. */
    started?: string;
    /** The time when the job has been stopped. */
    stopped?: string;
    /** The number of handled events. */
    handledEvents?: number;
    /** The number of handled assets. */
    handledAssets?: number;
    status?: SquidexApi.JobStatus;
}
