/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SquidexApi } from "@fern-api/squidex";
import * as core from "../../../../core";

export const TemplatesDto: core.serialization.ObjectSchema<serializers.TemplatesDto.Raw, SquidexApi.TemplatesDto> =
    core.serialization
        .object({
            items: core.serialization
                .list(core.serialization.lazyObject(async () => (await import("../../..")).TemplateDto))
                .optional(),
        })
        .extend(core.serialization.lazyObject(async () => (await import("../../..")).Resource));

export declare namespace TemplatesDto {
    interface Raw extends serializers.Resource.Raw {
        items?: serializers.TemplateDto.Raw[] | null;
    }
}
