/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Squidex } from "@squidex/squidex";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<serializers.teams.getAll.Response.Raw, Squidex.TeamDto[]> =
    core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).TeamDto));

export declare namespace Response {
    type Raw = serializers.TeamDto.Raw[];
}
