/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BackupsGetBackupContentV2Request {
    /**
     * The ID of the app.
     */
    appId?: string;
    /**
     * The name of the app.
     */
    app?: string;
}
