/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AddLanguageDto {
    /** The language to add. <span style="white-space: nowrap">`non-empty`</span> */
    language: string;
}
