/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateClientDto {
    /** The ID of the client. <span style="white-space: nowrap">`non-empty`</span> */
    id: string;
}
