/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export type AssetPreviewMode = "ImageAndFileName" | "Image" | "FileName";

export const AssetPreviewMode = {
    ImageAndFileName: "ImageAndFileName",
    Image: "Image",
    FileName: "FileName",
} as const;
