/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Squidex from "..";

export interface AssetFoldersDto {
    /** The total number of assets. */
    total?: number;
    /** The assets folders. */
    items?: Squidex.AssetFolderDto[];
    /** The path to the current folder. */
    path?: Squidex.AssetFolderDto[];
}
