/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Squidex from "..";

export interface AssetsDto {
    /** The total number of assets. */
    total: number;
    /** The assets. */
    items: Squidex.AssetDto[];
}
