/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AssignContributorDto {
    /** The id or email of the user to add to the app. <span style="white-space: nowrap">`non-empty`</span> */
    contributorId: string;
    /** The role of the contributor. */
    role?: string;
    /** Set to true to invite the user if he does not exist. */
    invite?: boolean;
}
