/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Squidex from "..";

export interface BackupJobsDto extends Squidex.Resource {
    /** The backups. */
    items: Squidex.BackupJobDto[];
}
