/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ChangePlanDto {
    /** The new plan id. <span style="white-space: nowrap">`non-empty`</span> */
    planId: string;
}
