/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CommentRuleActionDto {
    /** The comment text. <span style="white-space: nowrap">`non-empty`</span> */
    text: string;
    /** An optional client name. */
    client?: string;
}
