/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Squidex from "..";

export interface CommentsDto {
    /** The created comments including the updates. */
    createdComments?: Squidex.CommentDto[];
    /** The updates comments since the last version. */
    updatedComments?: Squidex.CommentDto[];
    /** The deleted comments since the last version. */
    deletedComments?: string[];
    /** The current version. */
    version: number;
}
