/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CommentRuleActionDto {
    /** The comment text. */
    text?: string;
    /** An optional client name. */
    client?: string;
}
