/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Squidex from "..";

export interface ContributorsDto {
    /** The contributors. */
    items?: Squidex.ContributorDto[];
    /** The maximum number of allowed contributors. */
    maxContributors?: number;
    meta?: Squidex.ContributorsMetadata;
}
