/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Squidex from "..";

export interface CreateRuleDto {
    trigger: Squidex.RuleTriggerDto;
    action: Squidex.RuleActionDto;
}
