/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DeepDetectRuleActionDto {
    /** The minimum probability for objects to be recognized (0 - 100). */
    minimumProbability: number;
    /** The maximum number of tags to use. */
    maximumTags: number;
}
