/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export type ImageFormat = "AVIF" | "BMP" | "GIF" | "JPEG" | "PNG" | "TGA" | "TIFF" | "WEBP";

export const ImageFormat = {
    Avif: "AVIF",
    Bmp: "BMP",
    Gif: "GIF",
    Jpeg: "JPEG",
    Png: "PNG",
    Tga: "TGA",
    Tiff: "TIFF",
    Webp: "WEBP",
} as const;
