/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *
 */
export type JobStatus = "Created" | "Started" | "Completed" | "Failed";

export const JobStatus = {
    Created: "Created",
    Started: "Started",
    Completed: "Completed",
    Failed: "Failed",
} as const;
