/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PatternDto {
    /** The name of the suggestion. */
    name: string;
    /** The regex pattern. */
    regex: string;
    /** The regex message. */
    message?: string;
}
