/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PrerenderRuleActionDto {
    /** The prerender token from your account. <span style="white-space: nowrap">`non-empty`</span> */
    token: string;
    /** The url to recache. <span style="white-space: nowrap">`non-empty`</span> */
    url: string;
}
