/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface QueryDto {
    /** The optional list of ids to query. */
    ids?: string[];
    /** The optional odata query. */
    oData?: string;
    q?: unknown;
    /** The parent id (for assets). */
    parentId?: string;
}
