/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Squidex from "..";

export interface SimulatedRuleEventsDto {
    /** The total number of simulated rule events. */
    total?: number;
    /** The simulated rule events. */
    items?: Squidex.SimulatedRuleEventDto[];
}
