/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SlackRuleActionDto {
    /** The slack webhook url. <span style="white-space: nowrap">`non-empty`</span> */
    webhookUrl: string;
    /** The text that is sent as message to slack. <span style="white-space: nowrap">`non-empty`</span> */
    text: string;
}
