/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Squidex from "..";

export interface TemplatesDto {
    /** The event consumers. */
    items: Squidex.TemplateDto[];
}
