/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Squidex from "..";

export interface TemplateDetailsDto extends Squidex.Resource {
    /** The details of the template. */
    details: string;
}
