/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpsertCommentDto {
    /** The comment text. */
    text: string;
    /** The url where the comment is created. */
    url?: string;
}
