/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Squidex from "..";

export interface UsersDto extends Squidex.Resource {
    /** The total number of users. */
    total: number;
    /** The users. */
    items: Squidex.UserDto[];
}
