/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Squidex from "..";

export interface WorkflowStepDto {
    /** The transitions. */
    transitions?: Record<string, Squidex.WorkflowTransitionDto>;
    /** The optional color. */
    color?: string;
    /** True if the content should be validated when moving to this step. */
    validate?: boolean;
    /** Indicates if updates should not be allowed. */
    noUpdate?: boolean;
    /** Optional expression that must evaluate to true when you want to prevent updates. */
    noUpdateExpression?: string;
    /** Optional list of roles to restrict the updates for users with these roles. */
    noUpdateRoles?: string[];
}
