/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WorkflowTransitionDto {
    /** The optional expression. */
    expression?: string;
    /** The optional restricted role. */
    roles?: string[];
}
