/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SquidexApi } from "@fern-api/squidex";

export interface TranslationDto {
    result?: SquidexApi.TranslationResultCode;
    /** The translated text. */
    text?: string;
}
