/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Squidex } from "@squidex/squidex";

export interface TemplatesDto extends Squidex.Resource {
    /** The event consumers. */
    items?: Squidex.TemplateDto[];
}
