/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Squidex } from "@fern-api/squidex";

export interface TemplateDetailsDto extends Squidex.Resource {
    /** The details of the template. */
    details: string;
}
