/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Squidex from "../../api";
import * as core from "../../core";

export const AppSettingsDto: core.serialization.ObjectSchema<serializers.AppSettingsDto.Raw, Squidex.AppSettingsDto> =
    core.serialization.object({
        patterns: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("..")).PatternDto))
            .optional(),
        editors: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("..")).EditorDto))
            .optional(),
        hideScheduler: core.serialization.boolean().optional(),
        hideDateTimeModeButton: core.serialization.boolean().optional(),
        version: core.serialization.number().optional(),
    });

export declare namespace AppSettingsDto {
    interface Raw {
        patterns?: serializers.PatternDto.Raw[] | null;
        editors?: serializers.EditorDto.Raw[] | null;
        hideScheduler?: boolean | null;
        hideDateTimeModeButton?: boolean | null;
        version?: number | null;
    }
}
