/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Squidex from "../../api";
import * as core from "../../core";

export const AssetFolderDto: core.serialization.ObjectSchema<serializers.AssetFolderDto.Raw, Squidex.AssetFolderDto> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        parentId: core.serialization.string().optional(),
        folderName: core.serialization.string().optional(),
        version: core.serialization.number().optional(),
    });

export declare namespace AssetFolderDto {
    interface Raw {
        id?: string | null;
        parentId?: string | null;
        folderName?: string | null;
        version?: number | null;
    }
}
