/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Squidex from "../../api";
import * as core from "../../core";

export const BooleanFieldPropertiesDto: core.serialization.ObjectSchema<
    serializers.BooleanFieldPropertiesDto.Raw,
    Squidex.BooleanFieldPropertiesDto
> = core.serialization.object({
    defaultValues: core.serialization.lazy(async () => (await import("..")).LocalizedValueOfNullableBoolean).optional(),
    defaultValue: core.serialization.boolean().optional(),
    inlineEditable: core.serialization.boolean(),
    editor: core.serialization.lazy(async () => (await import("..")).BooleanFieldEditor),
});

export declare namespace BooleanFieldPropertiesDto {
    interface Raw {
        defaultValues?: serializers.LocalizedValueOfNullableBoolean.Raw | null;
        defaultValue?: boolean | null;
        inlineEditable: boolean;
        editor: serializers.BooleanFieldEditor.Raw;
    }
}
