/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Squidex from "../../api";
import * as core from "../../core";

export const CallsUsagePerDateDto: core.serialization.ObjectSchema<
    serializers.CallsUsagePerDateDto.Raw,
    Squidex.CallsUsagePerDateDto
> = core.serialization.object({
    date: core.serialization.string(),
    totalCalls: core.serialization.number(),
    totalBytes: core.serialization.number(),
    averageElapsedMs: core.serialization.number(),
});

export declare namespace CallsUsagePerDateDto {
    interface Raw {
        date: string;
        totalCalls: number;
        totalBytes: number;
        averageElapsedMs: number;
    }
}
