/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Squidex from "../../api";
import * as core from "../../core";

export const CommentRuleActionDto: core.serialization.ObjectSchema<
    serializers.CommentRuleActionDto.Raw,
    Squidex.CommentRuleActionDto
> = core.serialization.object({
    text: core.serialization.string(),
    client: core.serialization.string(),
});

export declare namespace CommentRuleActionDto {
    interface Raw {
        text: string;
        client: string;
    }
}
