/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Squidex from "../../api";
import * as core from "../../core";

export const ContributorsMetadata: core.serialization.ObjectSchema<
    serializers.ContributorsMetadata.Raw,
    Squidex.ContributorsMetadata
> = core.serialization.object({
    isInvited: core.serialization.string(),
});

export declare namespace ContributorsMetadata {
    interface Raw {
        isInvited: string;
    }
}
