/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Squidex from "../../api";
import * as core from "../../core";

export const ContentsDto: core.serialization.ObjectSchema<serializers.ContentsDto.Raw, Squidex.ContentsDto> =
    core.serialization.object({
        total: core.serialization.number().optional(),
        items: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("..")).ContentDto))
            .optional(),
        statuses: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("..")).StatusInfoDto))
            .optional(),
    });

export declare namespace ContentsDto {
    interface Raw {
        total?: number | null;
        items?: serializers.ContentDto.Raw[] | null;
        statuses?: serializers.StatusInfoDto.Raw[] | null;
    }
}
