/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Squidex from "../../api";
import * as core from "../../core";

export const EmailRuleActionDto: core.serialization.ObjectSchema<
    serializers.EmailRuleActionDto.Raw,
    Squidex.EmailRuleActionDto
> = core.serialization.object({
    serverHost: core.serialization.string(),
    serverPort: core.serialization.number(),
    serverUsername: core.serialization.string(),
    serverPassword: core.serialization.string(),
    messageFrom: core.serialization.string(),
    messageTo: core.serialization.string(),
    messageSubject: core.serialization.string(),
    messageBody: core.serialization.string(),
});

export declare namespace EmailRuleActionDto {
    interface Raw {
        serverHost: string;
        serverPort: number;
        serverUsername: string;
        serverPassword: string;
        messageFrom: string;
        messageTo: string;
        messageSubject: string;
        messageBody: string;
    }
}
