/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Squidex from "../../api";
import * as core from "../../core";

export const GeolocationFieldPropertiesDto: core.serialization.ObjectSchema<
    serializers.GeolocationFieldPropertiesDto.Raw,
    Squidex.GeolocationFieldPropertiesDto
> = core.serialization.object({
    editor: core.serialization.lazy(async () => (await import("..")).GeolocationFieldEditor),
});

export declare namespace GeolocationFieldPropertiesDto {
    interface Raw {
        editor: serializers.GeolocationFieldEditor.Raw;
    }
}
