/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Squidex from "../../api";
import * as core from "../../core";

export const ManualRuleTriggerDto: core.serialization.ObjectSchema<
    serializers.ManualRuleTriggerDto.Raw,
    Squidex.ManualRuleTriggerDto
> = core.serialization.object({});

export declare namespace ManualRuleTriggerDto {
    interface Raw {}
}
