/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Squidex from "../../api";
import * as core from "../../core";

export const NotificationRuleActionDto: core.serialization.ObjectSchema<
    serializers.NotificationRuleActionDto.Raw,
    Squidex.NotificationRuleActionDto
> = core.serialization.object({
    user: core.serialization.string(),
    text: core.serialization.string(),
    url: core.serialization.string(),
    client: core.serialization.string(),
});

export declare namespace NotificationRuleActionDto {
    interface Raw {
        user: string;
        text: string;
        url: string;
        client: string;
    }
}
