/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Squidex from "../../api";
import * as core from "../../core";

export const OpenSearchRuleActionDto: core.serialization.ObjectSchema<
    serializers.OpenSearchRuleActionDto.Raw,
    Squidex.OpenSearchRuleActionDto
> = core.serialization.object({
    host: core.serialization.string(),
    indexName: core.serialization.string(),
    username: core.serialization.string(),
    password: core.serialization.string(),
    document: core.serialization.string(),
    delete: core.serialization.string(),
});

export declare namespace OpenSearchRuleActionDto {
    interface Raw {
        host: string;
        indexName: string;
        username: string;
        password: string;
        document: string;
        delete: string;
    }
}
