/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Squidex from "../../api";
import * as core from "../../core";

export const PlanChangedDto: core.serialization.ObjectSchema<serializers.PlanChangedDto.Raw, Squidex.PlanChangedDto> =
    core.serialization.object({
        redirectUri: core.serialization.string().optional(),
    });

export declare namespace PlanChangedDto {
    interface Raw {
        redirectUri?: string | null;
    }
}
