/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Squidex from "../../api";
import * as core from "../../core";

export const ReferralInfo: core.serialization.ObjectSchema<serializers.ReferralInfo.Raw, Squidex.ReferralInfo> =
    core.serialization.object({
        code: core.serialization.string(),
        earned: core.serialization.string(),
        condition: core.serialization.string(),
    });

export declare namespace ReferralInfo {
    interface Raw {
        code: string;
        earned: string;
        condition: string;
    }
}
