/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Squidex from "../../api";
import * as core from "../../core";

export const ResourcesDto: core.serialization.ObjectSchema<serializers.ResourcesDto.Raw, Squidex.ResourcesDto> =
    core.serialization.object({});

export declare namespace ResourcesDto {
    interface Raw {}
}
