/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Squidex from "../../api";
import * as core from "../../core";

export const SchemaType: core.serialization.Schema<serializers.SchemaType.Raw, Squidex.SchemaType> =
    core.serialization.enum_(["Default", "Singleton", "Component"]);

export declare namespace SchemaType {
    type Raw = "Default" | "Singleton" | "Component";
}
