/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Squidex from "../../api";
import * as core from "../../core";

export const SchemasDto: core.serialization.ObjectSchema<serializers.SchemasDto.Raw, Squidex.SchemasDto> =
    core.serialization.object({
        items: core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).SchemaDto)),
    });

export declare namespace SchemasDto {
    interface Raw {
        items: serializers.SchemaDto.Raw[];
    }
}
