/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Squidex from "../../api";
import * as core from "../../core";

export const SkipReason: core.serialization.Schema<serializers.SkipReason.Raw, Squidex.SkipReason> =
    core.serialization.enum_([
        "None",
        "ConditionDoesNotMatch",
        "ConditionPrecheckDoesNotMatch",
        "Disabled",
        "Failed",
        "FromRule",
        "NoAction",
        "NoTrigger",
        "TooOld",
        "WrongEvent",
        "WrongEventForTrigger",
    ]);

export declare namespace SkipReason {
    type Raw =
        | "None"
        | "ConditionDoesNotMatch"
        | "ConditionPrecheckDoesNotMatch"
        | "Disabled"
        | "Failed"
        | "FromRule"
        | "NoAction"
        | "NoTrigger"
        | "TooOld"
        | "WrongEvent"
        | "WrongEventForTrigger";
}
