/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Squidex from "../../api";
import * as core from "../../core";

export const TemplateDto: core.serialization.ObjectSchema<serializers.TemplateDto.Raw, Squidex.TemplateDto> =
    core.serialization.object({
        name: core.serialization.string().optional(),
        title: core.serialization.string().optional(),
        description: core.serialization.string().optional(),
        isStarter: core.serialization.boolean().optional(),
    });

export declare namespace TemplateDto {
    interface Raw {
        name?: string | null;
        title?: string | null;
        description?: string | null;
        isStarter?: boolean | null;
    }
}
