/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Squidex from "../../api";
import * as core from "../../core";

export const TypesenseRuleActionDto: core.serialization.ObjectSchema<
    serializers.TypesenseRuleActionDto.Raw,
    Squidex.TypesenseRuleActionDto
> = core.serialization.object({
    host: core.serialization.string(),
    indexName: core.serialization.string(),
    apiKey: core.serialization.string(),
    document: core.serialization.string(),
    delete: core.serialization.string(),
});

export declare namespace TypesenseRuleActionDto {
    interface Raw {
        host: string;
        indexName: string;
        apiKey: string;
        document: string;
        delete: string;
    }
}
