/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Squidex from "../../api";
import * as core from "../../core";

export const UpsertSchemaNestedFieldDto: core.serialization.ObjectSchema<
    serializers.UpsertSchemaNestedFieldDto.Raw,
    Squidex.UpsertSchemaNestedFieldDto
> = core.serialization.object({
    name: core.serialization.string(),
    isHidden: core.serialization.boolean(),
    isLocked: core.serialization.boolean(),
    isDisabled: core.serialization.boolean(),
    properties: core.serialization.lazy(async () => (await import("..")).FieldPropertiesDto),
});

export declare namespace UpsertSchemaNestedFieldDto {
    interface Raw {
        name: string;
        isHidden: boolean;
        isLocked: boolean;
        isDisabled: boolean;
        properties: serializers.FieldPropertiesDto.Raw;
    }
}
