/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Squidex } from "@fern-api/squidex";
import * as core from "../../../../core";

export const AnnotateAssetDto: core.serialization.ObjectSchema<
    serializers.AnnotateAssetDto.Raw,
    Squidex.AnnotateAssetDto
> = core.serialization.object({
    fileName: core.serialization.string().optional(),
    slug: core.serialization.string().optional(),
    isProtected: core.serialization.boolean().optional(),
    tags: core.serialization.list(core.serialization.string()).optional(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace AnnotateAssetDto {
    interface Raw {
        fileName?: string | null;
        slug?: string | null;
        isProtected?: boolean | null;
        tags?: string[] | null;
        metadata?: Record<string, unknown> | null;
    }
}
