/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SquidexApi } from "@fern-api/squidex";
import * as core from "../../../../core";

export const AssetFolderScope: core.serialization.Schema<
    serializers.AssetFolderScope.Raw,
    SquidexApi.AssetFolderScope
> = core.serialization.enum_(["PathAndItems", "Path", "Items"]);

export declare namespace AssetFolderScope {
    type Raw = "PathAndItems" | "Path" | "Items";
}
