/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SquidexApi } from "@fern-api/squidex";
import * as core from "../../../../core";

export const ResizeMode: core.serialization.Schema<serializers.ResizeMode.Raw, SquidexApi.ResizeMode> =
    core.serialization.enum_(["Crop", "CropUpsize", "Pad", "BoxPad", "Max", "Min", "Stretch"]);

export declare namespace ResizeMode {
    type Raw = "Crop" | "CropUpsize" | "Pad" | "BoxPad" | "Max" | "Min" | "Stretch";
}
