/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Squidex } from "@fern-api/squidex";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.statistics.getStorageSizeByDate.Response.Raw,
    Squidex.StorageUsagePerDateDto[]
> = core.serialization.list(
    core.serialization.lazyObject(async () => (await import("../../..")).StorageUsagePerDateDto)
);

export declare namespace Response {
    type Raw = serializers.StorageUsagePerDateDto.Raw[];
}
