/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SquidexApi } from "@fern-api/squidex";

export interface FeaturesDto {
    /** The latest features. */
    features: SquidexApi.FeatureDto[];
    /** The recent version. */
    version?: number;
}
