/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Squidex } from "@squidex/squidex";

export interface FeaturesDto {
    /** The latest features. */
    features: Squidex.FeatureDto[];
    /** The recent version. */
    version?: number;
}
