/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Squidex from "../../../../../api";
import * as core from "../../../../../core";

export const TranslateDto: core.serialization.Schema<serializers.TranslateDto.Raw, Squidex.TranslateDto> =
    core.serialization.object({
        text: core.serialization.string(),
        targetLanguage: core.serialization.string(),
        sourceLanguage: core.serialization.string().optional(),
    });

export declare namespace TranslateDto {
    interface Raw {
        text: string;
        targetLanguage: string;
        sourceLanguage?: string | null;
    }
}
