/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ContentChangedRuleTriggerSchemaDto {
    /** The ID of the schema. */
    schemaId?: string;
    /** Javascript condition when to trigger. */
    condition?: string;
}
