/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Squidex } from "@fern-api/squidex";

export interface ContentChangedRuleTriggerDto {
    /** The schema settings. */
    schemas?: Squidex.ContentChangedRuleTriggerSchemaDto[];
    /** Determines whether the trigger should handle all content changes events. */
    handleAll?: boolean;
}
