/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SquidexApi } from "@fern-api/squidex";

export interface CreateRuleDto {
    trigger: SquidexApi.RuleTriggerDto;
    action: SquidexApi.RuleActionDto;
}
