/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SquidexApi } from "@fern-api/squidex";

export interface RuleEventDto extends SquidexApi.Resource {
    /** The ID of the event. */
    id?: string;
    /** The time when the event has been created. */
    created?: string;
    /** The description. */
    description: string;
    /** The name of the event. */
    eventName: string;
    /** The last dump. */
    lastDump?: string;
    /** The number of calls. */
    numCalls?: number;
    /** The next attempt. */
    nextAttempt?: string;
    result?: SquidexApi.RuleResult;
    jobResult?: SquidexApi.RuleJobResult;
}
