/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SquidexApi } from "@fern-api/squidex";
import * as core from "../../../../core";

export const TransferToTeamDto: core.serialization.ObjectSchema<
    serializers.TransferToTeamDto.Raw,
    SquidexApi.TransferToTeamDto
> = core.serialization.object({
    teamId: core.serialization.string().optional(),
});

export declare namespace TransferToTeamDto {
    interface Raw {
        teamId?: string | null;
    }
}
