/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Squidex } from "@squidex/squidex";
import * as core from "../../../../core";

export const UpdateAppDto: core.serialization.ObjectSchema<serializers.UpdateAppDto.Raw, Squidex.UpdateAppDto> =
    core.serialization.object({
        label: core.serialization.string().optional(),
        description: core.serialization.string().optional(),
    });

export declare namespace UpdateAppDto {
    interface Raw {
        label?: string | null;
        description?: string | null;
    }
}
