/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Squidex } from "@fern-api/squidex";
import * as core from "../../../../core";

export const HistoryEventDto: core.serialization.ObjectSchema<
    serializers.HistoryEventDto.Raw,
    Squidex.HistoryEventDto
> = core.serialization.object({
    message: core.serialization.string(),
    eventType: core.serialization.string(),
    actor: core.serialization.string(),
    eventId: core.serialization.string().optional(),
    created: core.serialization.string().optional(),
    version: core.serialization.number().optional(),
});

export declare namespace HistoryEventDto {
    interface Raw {
        message: string;
        eventType: string;
        actor: string;
        eventId?: string | null;
        created?: string | null;
        version?: number | null;
    }
}
