/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateAppDto {
    /** The optional label of your app. */
    label?: string;
    /** The optional description of your app. */
    description?: string;
}
