/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateRoleDto {
    /** Associated list of permissions. */
    permissions: string[];
    /** Associated list of UI properties. */
    properties?: Record<string, unknown>;
}
