/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { SquidexApi } from "@fern-api/squidex";

export interface UpdateWorkflowDto {
    /** The name of the workflow. */
    name?: string;
    /** The workflow steps. */
    steps: Record<string, SquidexApi.WorkflowStepDto>;
    /** The schema ids. */
    schemaIds?: string[];
    /** The initial step. */
    initial: string;
}
