/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Squidex } from "@fern-api/squidex";
import * as core from "../../../../core";

export const CommentRuleTriggerDto: core.serialization.ObjectSchema<
    serializers.CommentRuleTriggerDto.Raw,
    Squidex.CommentRuleTriggerDto
> = core.serialization.object({
    condition: core.serialization.string().optional(),
});

export declare namespace CommentRuleTriggerDto {
    interface Raw {
        condition?: string | null;
    }
}
