/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Squidex } from "@squidex/squidex";
import * as core from "../../../../core";

export const ElasticSearchRuleActionDto: core.serialization.ObjectSchema<
    serializers.ElasticSearchRuleActionDto.Raw,
    Squidex.ElasticSearchRuleActionDto
> = core.serialization.object({
    host: core.serialization.string(),
    indexName: core.serialization.string(),
    username: core.serialization.string().optional(),
    password: core.serialization.string().optional(),
    document: core.serialization.string().optional(),
    delete: core.serialization.string().optional(),
});

export declare namespace ElasticSearchRuleActionDto {
    interface Raw {
        host: string;
        indexName: string;
        username?: string | null;
        password?: string | null;
        document?: string | null;
        delete?: string | null;
    }
}
