/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Squidex } from "@squidex/squidex";
import * as core from "../../../../core";

export const UsageRuleTriggerDto: core.serialization.ObjectSchema<
    serializers.UsageRuleTriggerDto.Raw,
    Squidex.UsageRuleTriggerDto
> = core.serialization.object({
    limit: core.serialization.number().optional(),
    numDays: core.serialization.number().optional(),
});

export declare namespace UsageRuleTriggerDto {
    interface Raw {
        limit?: number | null;
        numDays?: number | null;
    }
}
