/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { SquidexApi } from "@fern-api/squidex";
import * as core from "../../../../core";

export const SearchResultType: core.serialization.Schema<
    serializers.SearchResultType.Raw,
    SquidexApi.SearchResultType
> = core.serialization.enum_(["Asset", "Content", "Dashboard", "Setting", "Rule", "Schema"]);

export declare namespace SearchResultType {
    type Raw = "Asset" | "Content" | "Dashboard" | "Setting" | "Rule" | "Schema";
}
