/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const SquidexApiEnvironment = {
    Production: "https://cloud.squidex.io",
} as const;

export type SquidexApiEnvironment = typeof SquidexApiEnvironment.Production;
