/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Squidex from "../../../..";

export interface CreateSchemaDto extends Squidex.UpsertSchemaDto {
    /** The name of the schema. <span style="white-space: nowrap">`non-empty`</span> */
    name: string;
    type?: Squidex.SchemaType;
    /** Set to true to allow a single content item only. */
    isSingleton?: boolean;
}
