/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Squidex } from "@fern-api/squidex";
import * as core from "../../../../core";

export const CommentDto: core.serialization.ObjectSchema<serializers.CommentDto.Raw, Squidex.CommentDto> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        time: core.serialization.string(),
        user: core.serialization.string(),
        text: core.serialization.string(),
        url: core.serialization.string().optional(),
    });

export declare namespace CommentDto {
    interface Raw {
        id?: string | null;
        time: string;
        user: string;
        text: string;
        url?: string | null;
    }
}
