/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Squidex } from "@fern-api/squidex";
import * as core from "../../../../core";

export const ResourceLink: core.serialization.ObjectSchema<serializers.ResourceLink.Raw, Squidex.ResourceLink> =
    core.serialization.object({
        href: core.serialization.string(),
        method: core.serialization.string(),
        metadata: core.serialization.string().optional(),
    });

export declare namespace ResourceLink {
    interface Raw {
        href: string;
        method: string;
        metadata?: string | null;
    }
}
