name: test
concurrency: build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare - Checkout
        uses: actions/checkout@v4.0.0

      - name: Test - Start Compose
        run: docker-compose up -d
        working-directory: tests

      - name: Test - RUN
        uses: kohlerdominik/docker-run-action@v2.0.0
        with:
          image: node
          environment: |
            CONFIG__WAIT=60
            CONFIG__SERVER__URL=http://localhost:8080
          default_network: host
          options: --name test1
          volumes: ${{ github.workspace }}:/src
          run: |
            cd /src
            yarn install
            ./test.sh
       
      - name: Test - Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2.2.1
        with:
         images: 'squidex,squidex/resizer'
         tail: '100'

      - name: Test - Cleanup
        if: always()
        run: docker-compose down
        working-directory: tests
