/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ChangeStatusDto {
    /**
     * Return unpublished content items.
     */
    unpublished?: boolean;
    /**
     * Only resolve these languages (comma-separated).
     */
    languages?: string;
    /** The new status. <span style="white-space: nowrap">`non-empty`</span> */
    status: string;
    /** The due time. */
    dueTime?: string;
    /** True to check referrers of this content. */
    checkReferrers?: boolean;
}
