/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ContentsGetReferencingRequest {
    /**
     * The optional json query.
     */
    q?: string;
    /**
     * Return unpublished content items.
     */
    flatten?: boolean;
    /**
     * Only resolve these languages (comma-separated).
     */
    languages?: string;
    /**
     * Do not return the total amount, if it would be slow.
     */
    noSlowTotal?: boolean;
    /**
     * Do not return the total amount.
     */
    noTotal?: boolean;
}
