/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Squidex from "../../../..";

export interface ContentsPostUpsertContentRequest {
    status?: string;
    patch?: boolean;
    publish?: boolean;
    body: Record<string, Squidex.ContentFieldData>;
}
