/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ContentsGetAllContentsRequest {
    /**
     * The list of ids to query.
     */
    ids?: string;
    /**
     * The start of the schedule.
     */
    scheduleFrom?: Date;
    /**
     * The end of the schedule.
     */
    scheduleTo?: Date;
    /**
     * The ID of the referencing content item.
     */
    referencing?: string;
    /**
     * The ID of the reference content item.
     */
    references?: string;
    /**
     * The optional json query.
     */
    q?: string;
    /**
     * The list of content fields (comma-separated).
     */
    fields?: string;
    /**
     * Provide the data as flat object.
     */
    flatten?: boolean;
    /**
     * The list of languages to resolve (comma-separated).
     */
    languages?: string;
    /**
     * Do not return the total amount, if it would be slow.
     */
    noSlowTotal?: boolean;
    /**
     * Do not return the total amount.
     */
    noTotal?: boolean;
    /**
     * Return unpublished content items.
     */
    unpublished?: boolean;
}
