/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ContentsGetContentVersionRequest {
    /**
     * Return unpublished content items.
     */
    unpublished?: boolean;
    /**
     * The list of languages to resolve (comma-separated).
     */
    languages?: string;
}
