/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ContentsPostGraphQlBatchRequest {
    /**
     * Return unpublished content items.
     */
    unpublished?: boolean;
    body?: unknown;
}
