/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ContentsGetGraphQl2Request {
    /**
     * Return unpublished content items.
     */
    unpublished?: boolean;
}
